// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/chat.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import empty "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Types
type Login struct {
	Username             string   `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Login) Reset()         { *m = Login{} }
func (m *Login) String() string { return proto.CompactTextString(m) }
func (*Login) ProtoMessage()    {}
func (*Login) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_9ee60ded635f8960, []int{0}
}
func (m *Login) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Login.Unmarshal(m, b)
}
func (m *Login) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Login.Marshal(b, m, deterministic)
}
func (dst *Login) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Login.Merge(dst, src)
}
func (m *Login) XXX_Size() int {
	return xxx_messageInfo_Login.Size(m)
}
func (m *Login) XXX_DiscardUnknown() {
	xxx_messageInfo_Login.DiscardUnknown(m)
}

var xxx_messageInfo_Login proto.InternalMessageInfo

func (m *Login) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Login) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
	Mode                 int32    `protobuf:"varint,2,opt,name=Mode" json:"Mode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_9ee60ded635f8960, []int{1}
}
func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (dst *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(dst, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *LoginResponse) GetMode() int32 {
	if m != nil {
		return m.Mode
	}
	return 0
}

type Message struct {
	Sender               string   `protobuf:"bytes,1,opt,name=sender" json:"sender,omitempty"`
	Text                 string   `protobuf:"bytes,2,opt,name=text" json:"text,omitempty"`
	Group                int32    `protobuf:"varint,4,opt,name=group" json:"group,omitempty"`
	LoginID              string   `protobuf:"bytes,5,opt,name=LoginID" json:"LoginID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_9ee60ded635f8960, []int{2}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (dst *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(dst, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *Message) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Message) GetGroup() int32 {
	if m != nil {
		return m.Group
	}
	return 0
}

func (m *Message) GetLoginID() string {
	if m != nil {
		return m.LoginID
	}
	return ""
}

type Logout struct {
	Username             string   `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Logout) Reset()         { *m = Logout{} }
func (m *Logout) String() string { return proto.CompactTextString(m) }
func (*Logout) ProtoMessage()    {}
func (*Logout) Descriptor() ([]byte, []int) {
	return fileDescriptor_chat_9ee60ded635f8960, []int{3}
}
func (m *Logout) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Logout.Unmarshal(m, b)
}
func (m *Logout) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Logout.Marshal(b, m, deterministic)
}
func (dst *Logout) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Logout.Merge(dst, src)
}
func (m *Logout) XXX_Size() int {
	return xxx_messageInfo_Logout.Size(m)
}
func (m *Logout) XXX_DiscardUnknown() {
	xxx_messageInfo_Logout.DiscardUnknown(m)
}

var xxx_messageInfo_Logout proto.InternalMessageInfo

func (m *Logout) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func init() {
	proto.RegisterType((*Login)(nil), "proto.Login")
	proto.RegisterType((*LoginResponse)(nil), "proto.LoginResponse")
	proto.RegisterType((*Message)(nil), "proto.Message")
	proto.RegisterType((*Logout)(nil), "proto.Logout")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ChatClient is the client API for Chat service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ChatClient interface {
	LoginCred(ctx context.Context, in *Login, opts ...grpc.CallOption) (*LoginResponse, error)
	TransferMessage(ctx context.Context, opts ...grpc.CallOption) (Chat_TransferMessageClient, error)
	LogoutCred(ctx context.Context, in *Logout, opts ...grpc.CallOption) (*empty.Empty, error)
}

type chatClient struct {
	cc *grpc.ClientConn
}

func NewChatClient(cc *grpc.ClientConn) ChatClient {
	return &chatClient{cc}
}

func (c *chatClient) LoginCred(ctx context.Context, in *Login, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/proto.Chat/LoginCred", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatClient) TransferMessage(ctx context.Context, opts ...grpc.CallOption) (Chat_TransferMessageClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Chat_serviceDesc.Streams[0], "/proto.Chat/TransferMessage", opts...)
	if err != nil {
		return nil, err
	}
	x := &chatTransferMessageClient{stream}
	return x, nil
}

type Chat_TransferMessageClient interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ClientStream
}

type chatTransferMessageClient struct {
	grpc.ClientStream
}

func (x *chatTransferMessageClient) Send(m *Message) error {
	return x.ClientStream.SendMsg(m)
}

func (x *chatTransferMessageClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *chatClient) LogoutCred(ctx context.Context, in *Logout, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/proto.Chat/LogoutCred", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatServer is the server API for Chat service.
type ChatServer interface {
	LoginCred(context.Context, *Login) (*LoginResponse, error)
	TransferMessage(Chat_TransferMessageServer) error
	LogoutCred(context.Context, *Logout) (*empty.Empty, error)
}

func RegisterChatServer(s *grpc.Server, srv ChatServer) {
	s.RegisterService(&_Chat_serviceDesc, srv)
}

func _Chat_LoginCred_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Login)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).LoginCred(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Chat/LoginCred",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).LoginCred(ctx, req.(*Login))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chat_TransferMessage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChatServer).TransferMessage(&chatTransferMessageServer{stream})
}

type Chat_TransferMessageServer interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ServerStream
}

type chatTransferMessageServer struct {
	grpc.ServerStream
}

func (x *chatTransferMessageServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func (x *chatTransferMessageServer) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Chat_LogoutCred_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Logout)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).LogoutCred(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Chat/LogoutCred",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).LogoutCred(ctx, req.(*Logout))
	}
	return interceptor(ctx, in, info, handler)
}

var _Chat_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Chat",
	HandlerType: (*ChatServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LoginCred",
			Handler:    _Chat_LoginCred_Handler,
		},
		{
			MethodName: "LogoutCred",
			Handler:    _Chat_LogoutCred_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TransferMessage",
			Handler:       _Chat_TransferMessage_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/chat.proto",
}

func init() { proto.RegisterFile("proto/chat.proto", fileDescriptor_chat_9ee60ded635f8960) }

var fileDescriptor_chat_9ee60ded635f8960 = []byte{
	// 302 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0xc1, 0x4e, 0xc2, 0x40,
	0x10, 0x86, 0x29, 0xa1, 0x20, 0x13, 0x41, 0x33, 0x21, 0xa4, 0xa9, 0x17, 0xb3, 0xf1, 0xc0, 0xa9,
	0xa8, 0xc4, 0x78, 0xf4, 0x00, 0x1e, 0x48, 0xe0, 0x42, 0x7c, 0x81, 0x62, 0x87, 0xc5, 0x44, 0x3a,
	0xcd, 0xee, 0x36, 0xea, 0x23, 0xf9, 0x96, 0x86, 0xd9, 0xad, 0x1a, 0x0f, 0x9e, 0x3a, 0xdf, 0xce,
	0xfc, 0xff, 0xcc, 0x74, 0xe0, 0xbc, 0x32, 0xec, 0x78, 0xfa, 0xbc, 0xcf, 0x5d, 0x26, 0x21, 0xc6,
	0xf2, 0x49, 0x2f, 0x34, 0xb3, 0x7e, 0xa5, 0xa9, 0xd0, 0xb6, 0xde, 0x4d, 0xe9, 0x50, 0xb9, 0x0f,
	0x5f, 0xa3, 0x1e, 0x20, 0x5e, 0xb1, 0x7e, 0x29, 0x31, 0x85, 0x93, 0xda, 0x92, 0x29, 0xf3, 0x03,
	0x25, 0xd1, 0x65, 0x34, 0xe9, 0x6f, 0xbe, 0xf9, 0x98, 0xab, 0x72, 0x6b, 0xdf, 0xd8, 0x14, 0x49,
	0xdb, 0xe7, 0x1a, 0x56, 0x33, 0x18, 0x88, 0xc1, 0x86, 0x6c, 0xc5, 0xa5, 0x25, 0x1c, 0x42, 0x7b,
	0xb9, 0x08, 0x16, 0xed, 0xe5, 0x02, 0x11, 0x3a, 0x6b, 0x2e, 0x48, 0x84, 0xf1, 0x46, 0x62, 0x45,
	0xd0, 0x5b, 0x93, 0xb5, 0xb9, 0x26, 0x1c, 0x43, 0xd7, 0x52, 0x59, 0x90, 0x09, 0x92, 0x40, 0x47,
	0x99, 0xa3, 0x77, 0x17, 0xfa, 0x49, 0x8c, 0x23, 0x88, 0xb5, 0xe1, 0xba, 0x4a, 0x3a, 0xe2, 0xe5,
	0x01, 0x13, 0xe8, 0xc9, 0x04, 0xcb, 0x45, 0x12, 0x4b, 0x71, 0x83, 0xea, 0x0a, 0xba, 0x2b, 0xd6,
	0x5c, 0xbb, 0xff, 0xb6, 0xbb, 0xfd, 0x8c, 0xa0, 0x33, 0xdf, 0xe7, 0x0e, 0x6f, 0xa0, 0x2f, 0xca,
	0xb9, 0xa1, 0x02, 0x4f, 0xfd, 0x0f, 0xca, 0xe4, 0x25, 0x1d, 0xfd, 0xa6, 0x66, 0x55, 0xd5, 0xc2,
	0x7b, 0x38, 0x7b, 0x32, 0x79, 0x69, 0x77, 0x64, 0x9a, 0x85, 0x86, 0xa1, 0x34, 0x70, 0xfa, 0x87,
	0x55, 0x6b, 0x12, 0x5d, 0x47, 0x78, 0x07, 0xe0, 0x47, 0x93, 0x66, 0x83, 0x1f, 0x7b, 0xae, 0x5d,
	0x3a, 0xce, 0xfc, 0xc9, 0xb2, 0xe6, 0x64, 0xd9, 0xe3, 0xf1, 0x64, 0xaa, 0xb5, 0xed, 0xca, 0xcb,
	0xec, 0x2b, 0x00, 0x00, 0xff, 0xff, 0xd7, 0xef, 0x06, 0xcc, 0xed, 0x01, 0x00, 0x00,
}
